package V2.util;

public enum ProcedureFlag {
    CHECK_CLIENT_TYPE,
    SEND_MATRICES,
    RECEIVE_MATRICES,
    PRINT_MATRICES,
    RECEIVE_SERVER_INFO,
    SEND_RESULT,
    PRINT_CLIENT_INFO,
    RECEIVE_STRATEGY_TYPE,
    TEST_SERVER_TO_CLIENT
}
